---
application:
  name: "apps"
  project: "the-siths"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Ice"
  version: "12"
routers:
- name: "main-apps"
  routes:
  - application_name: "apps"
    paths:
    - "/*"
